"""Record croniter 6.0.0's reading of the cron expressions install/jobs.ts handles.

Generates skills/index-network/scripts/tests/fixtures/croniter-6.0.0.json, the
fixture for the differential test in job-settings.test.ts. Not a test and not
needed to run the suite: run once with the Python that Hermes v2026.9.24 uses
(croniter 6.0.0), after croniter-fixture-input.ts wrote the input file:

    <hermes-venv>/bin/python croniter_fixture.py <input.json> <output.json>

For every expression it records croniter's expansion of the expression as
given and of the canonical form the tool would send (``x``: one string per
field, ``*`` or the values joined by commas), whether croniter refuses it
(constructor error) or finds no next run (``nextErr``), and for the report
expressions the next five runs after 2026-10-05 00:00 (naive wall time, as
Hermes hands croniter its zone's wall clock).
"""

import json
import sys
from datetime import datetime

import croniter as croniter_module
from croniter import croniter

BASE = datetime(2026, 10, 5, 0, 0)


def fields(expanded):
    return [
        "*" if field == ["*"] else ",".join(str(value) for value in field)
        for field in expanded[:5]
    ]


def reading(expr, with_next):
    if expr is None:
        return None
    out = {"x": None, "err": None, "nextErr": None}
    try:
        it = croniter(expr, BASE)
    except Exception as exc:  # noqa: BLE001 - the error class is the record
        out["err"] = type(exc).__name__
        return out
    out["x"] = fields(it.expanded)
    try:
        runs = [it.get_next(datetime).strftime("%Y-%m-%d %H:%M") for _ in range(5)]
        if with_next:
            out["next"] = runs
    except Exception as exc:  # noqa: BLE001
        out["nextErr"] = type(exc).__name__
    return out


def main():
    source, target = sys.argv[1], sys.argv[2]
    with open(source, encoding="utf-8") as handle:
        data = json.load(handle)
    version = getattr(croniter_module, "__version__", None)
    if version is None:
        from importlib.metadata import version as dist_version

        version = dist_version("croniter")
    report = []
    for row in data["report"]:
        report.append({
            "e": row["e"],
            "c": row["c"],
            "input": reading(row["e"], False),
            "canonical": reading(row["c"], True),
        })
    sweep = []
    for row in data["sweep"]:
        given = reading(row["e"], False)
        canonical = reading(row["c"], False)
        entry = [row["e"], row["c"], "|".join(canonical["x"]) if canonical and canonical["x"] else None]
        if given and given["x"] and canonical and given["x"] != canonical["x"]:
            entry.append("|".join(given["x"]))
        sweep.append(entry)
    out = {
        "croniter": version,
        "base": BASE.isoformat(),
        "note": "Generated by croniter_fixture.py from croniter-fixture-input.ts; do not edit by hand.",
        "report": report,
        "sweep": sweep,
    }
    with open(target, "w", encoding="utf-8") as handle:
        json.dump(out, handle, separators=(",", ":"))
        handle.write("\n")
    print(f"croniter {version}: {len(report)} report, {len(sweep)} sweep -> {target}")


if __name__ == "__main__":
    main()
